name: Additional Arguments in Push

on: push

jobs:

  read-argument:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Patch version
        if: contains(github.event.head_commit.message, 'version-patch')
        run: echo "New patch version"

      - name: Minor version
        if: contains(github.event.head_commit.message, 'version-minor')
        run: echo "New minor version"
      
      - name: Major version
        if: contains(github.event.head_commit.message, 'version-major')
        run: echo "New major version"
  
  
