name: Additional Arguments in Push

on: push

jobs:

  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Docker image version
        run: |
          IMAGE_NAME="your-docker-image"
          IMAGE_TAG=$(git describe --tags --abbrev=0 --match "${IMAGE_NAME}-*" | cut -d "-" -f2)
          VERSION=$(docker inspect --format='{{index .Config.Labels "version"}}' "${IMAGE_NAME}:${IMAGE_TAG}")
          MAJOR=$(echo $VERSION | cut -d. -f1)
          MINOR=$(echo $VERSION | cut -d. -f2)
          PATCH=$(echo $VERSION | cut -d. -f3)
        env:
          MAJOR: $MAJOR
          MINOR: $MINOR
          PATCH: $PATCH
      - name: Print version variables
        run: |
          echo "MAJOR version: $MAJOR"
          echo "MINOR version: $MINOR"
          echo "PATCH version: $PATCH"

  read-argument:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Patch version
        if: contains(github.event.head_commit.message, 'version-patch')
        run: echo "New patch version"

      - name: Minor version
        if: contains(github.event.head_commit.message, 'version-minor')
        run: echo "New minor version"
      
      - name: Major version
        if: contains(github.event.head_commit.message, 'version-major')
        run: echo "New major version"
  
  
