name: Read and update artifacts

on:
  push:
    branches: [main]

jobs:
  update-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: read_json
        id: version
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: ".github/artifacts/version.json"
          
      - run: |
          echo "MAJOR=${{steps.version.outputs.major}}" >> $GITHUB_ENV
          echo "MINOR=${{steps.version.outputs.minor}}" >> $GITHUB_ENV
          echo "PATCH=${{steps.version.outputs.patch}}" >> $GITHUB_ENV

      - run: |
          echo $MAJOR
          echo $MINOR
          echo $PATCH
          
      - name: add 1
        run: echo "MINOR=$(($MINOR+1))" >> $GITHUB_ENV
          
      - name: write_json
        id: create-json
        uses: jsdaniell/create-json@v1
        with:
          name: "version.json"
          json: '{ "major": $MAJOR, "minor": $MINOR, "patch": $PATCH }'
          dir: '.github/artifacts/'
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update version.json (automated)
