name: Read and update artifacts

on:
  push:
    branches: [main]

jobs:
  new-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      
      - name: Check if file exists
        run: |
          if [ -f .github/artifacts/version.json ]; then
            echo "File exists"
            echo "FILE_EXISTS=true" >> $GITHUB_ENV
          else
            mkdir -p .github/artifacts
            echo "File does not exist"
            echo "FILE_EXISTS=false" >> $GITHUB_ENV
          fi
          
      - run: echo ${{ env.FILE_EXISTS }}
          
      - name: Create new file if necessary
        if: ${{ env.FILE_EXISTS == 'false' }} 
        uses: jsdaniell/create-json@v1
        with:
          name: "version.json"
          json: '{ "major": 0, "minor": 0, "patch": 0 }'
          dir: '.github/artifacts/'
      
      - name: read_json
        id: version
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: ".github/artifacts/version.json"
          
      - run: |
          echo "MAJOR=${{steps.version.outputs.major}}" >> $GITHUB_ENV
          echo "MINOR=${{steps.version.outputs.minor}}" >> $GITHUB_ENV
          echo "PATCH=${{steps.version.outputs.patch}}" >> $GITHUB_ENV

      - run: |
          echo ${{ env.MINOR }}
          echo ${{ env.MINOR }}
          echo ${{ env.MINOR }}
          
      - name: add 1
        run: echo "MINOR=$((${{ env.MINOR }}+1))" >> $GITHUB_ENV
          
      - name: write_json
        id: create-json
        uses: jsdaniell/create-json@v1
        with:
          name: "version.json"
          json: '{ "major": ${{ env.MAJOR }}, "minor": ${{ env.MINOR }}, "patch": ${{ env.PATCH }} }'
          dir: '.github/artifacts/'
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: update version.json (automated)
