name: Read and update artifacts

on:
  push:
    branches: [main]

jobs:
  update-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir -p artifact/major.txt
      - run: echo 0 > artifact/major.txt

      - uses: actions/upload-artifact@v3
        with:
          name: major
          path: artifact/major.txt
