name: Read and update artifacts

on:
  push:
    branches: [main]

jobs:
  update-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: read_json
        id: variables
        uses: zoexx/github-action-json-file-properties@release
        with:
          file_path: ".github/artifacts/variables.json"
          
        env:
          MAJOR: ${{steps.variables.outputs.major}}
          MINOR: ${{steps.variables.outputs.minor}}
          PATCH: ${{steps.variables.outputs.patch}}

      - run: |
          echo $MAJOR
          echo $MINOR
          echo $PATCH       
          
      - name: write_json
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "variables.json"
          json: '{ "major": ${{steps.variables.outputs.major}}, "minor": ${{steps.variables.outputs.minor}}, "patch": ${{steps.variables.outputs.patch}} }'
          dir: '.github/artifacts/'
